### ISSUE TITLE
Webhooks for ticket

### ISSUE THREAD

**Issue by naysakiu** [Jexactyl/Jexactyl#298] opened 2023-05-25 16:13 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hi 

As a hosting provider some customers are creating ticket on the game panel , and it will be nice if to add a optional webhook for tickets, which will send a message on a discord server for ticket creation , reply etc

**Comment by camwhi-te** [comment] 2023-05-25 21:58
Duplicate of #245

**Closed as completed by camwhi-te** 2023-05-25 21:58 UTC
Labels: type: feature request, priority: low
