### ISSUE TITLE
Unable to view servers via client UI

### ISSUE THREAD

**Issue by TheBoiCJ** [Jexactyl/Jexactyl#359] opened 2024-12-22 19:27 UTC
### Current Behavior

When clicking on a server, The application throws a error.

### Expected Behavior

The server page loads and allows management.

### Steps to Reproduce

1. Setup Everest
2. Add a Node
3. Create a server
4. Go to client UI
5. Click on server

### Panel Version

v4.0.0-beta1

### Wings Version

1.11.13

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by TheBoiCJ** [comment] 2024-12-22 19:28
@camwhit-e

**Comment by camwhi-te** [comment] 2024-12-22 20:59
@TheBoiCJ Would be great if you could upload browser console logs as that'll be where the actual error is thrown. I'm not able to reproduce though

**Comment by TheBoiCJ** [comment] 2024-12-26 23:25
Hello, @camwhit-e. Sorry for the delay, As i have been working on other projects. Here are the logs:
```
Array []
DashboardRouter-95904582.js:1:16283
Error: useLocation() may be used only in the context of a <Router> component.
    j http://10.0.0.36:8734/build/assets/ActivityLogEntry-1b1a85cf.js:2
    de http://10.0.0.36:8734/build/assets/ActivityLogEntry-1b1a85cf.js:2
    Zs http://10.0.0.36:8734/build/assets/ActivityLogEntry-1b1a85cf.js:4
    ym http://10.0.0.36:8734/build/assets/routes-52f77df7.js:20
    zm http://10.0.0.36:8734/build/assets/index-6f322507.js:38
    W5 http://10.0.0.36:8734/build/assets/index-6f322507.js:40
    H5 http://10.0.0.36:8734/build/assets/index-6f322507.js:40
    bE http://10.0.0.36:8734/build/assets/index-6f322507.js:40
    nu http://10.0.0.36:8734/build/assets/index-6f322507.js:40
    Ap http://10.0.0.36:8734/build/assets/index-6f322507.js:40
    qv http://10.0.0.36:8734/build/assets/index-6f322507.js:40
    ni http://10.0.0.36:8734/build/assets/index-6f322507.js:38
    Ot http://10.0.0.36:8734/build/assets/index-6f322507.js:40
index-6f322507.js:40:161
Error: useLocation() may be used only in the context of a <Router> component.
    j http://10.0.0.36:8734/build/assets/ActivityLogEntry-1b1a85cf.js:2
    de http://10.0.0.36:8734/build/assets/ActivityLogEntry-1b1a85cf.js:2
    Zs http://10.0.0.36:8734/build/assets/ActivityLogEntry-1b1a85cf.js:4
    ym http://10.0.0.36:8734/build/assets/routes-52f77df7.js:20
    zm http://10.0.0.36:8734/build/assets/index-6f322507.js:38
    W5 http://10.0.0.36:8734/build/assets/index-6f322507.js:40
    H5 http://10.0.0.36:8734/build/assets/index-6f322507.js:40
    bE http://10.0.0.36:8734/build/assets/index-6f322507.js:40
    nu http://10.0.0.36:8734/build/assets/index-6f322507.js:40
    Ap http://10.0.0.36:8734/build/assets/index-6f322507.js:40
    qv http://10.0.0.36:8734/build/assets/index-6f322507.js:40
    ni http://10.0.0.36:8734/build/assets/index-6f322507.js:38
    Ot http://10.0.0.36:8734/build/assets/index-6f322507.js:40
index-6f322507.js:74:61217
Partitioned cookie or storage access was provided to “https://js.stripe.com/v3/m-outer-3437aaddcdf6922d623e172c2d6f9278.html#url=http%3A%2F%2F10.0.0.36%3A8734%2Faccount%2Factivity&title=Dashboard&referrer=http%3A%2F%2F10.0.0.36%3A8734%2Fauth%2Flogin&muid=9b5af9d8-a41d-4a05-8ed7-828292675e3fe23545&sid=2b73ab92-d1db-46ab-965d-0def8756aad648c26f&version=6&preview=false” because it is loaded in the third-party context and dynamic state partitioning is enabled.
Partitioned cookie or storage access was provided to “https://m.stripe.network/inner.html#url=http%3A%2F%2F10.0.0.36%3A8734%2Faccount%2Factivity&title=Dashboard&referrer=http%3A%2F%2F10.0.0.36%3A8734%2Fauth%2Flogin&muid=9b5af9d8-a41d-4a05-8ed7-828292675e3fe23545&sid=2b73ab92-d1db-46ab-965d-0def8756aad648c26f&version=6&preview=false” because it is loaded in the third-party context and dynamic state partitioning is enabled.
Cookie warnings 2
```

**Comment by camwhi-te** [comment] 2024-12-27 01:38
Honestly I'm not able to see where this issue is coming from by searching the codebase for useLocation() hook usage being outside of the app router. Can you please attempt to upgrade to `v4.0.0-beta2` and see if the problem is resolved? Thanks

**Comment by TheBoiCJ** [comment] 2024-12-28 19:47
@camwhit-e A friend of mine is getting the exact same error with his instance

**Comment by TheBoiCJ** [comment] 2024-12-28 20:05
Also same issue when upgrading, And running a build

**Comment by TheBoiCJ** [comment] 2024-12-28 20:15
I figured it out i think, you were using react-router instead of react-router-dom

**Comment by TheBoiCJ** [comment] 2024-12-28 20:15
@camwhit-e

**Comment by camwhi-te** [comment] 2024-12-28 21:19
Closed in merge

**Closed as completed by camwhi-te** 2024-12-28 21:19 UTC
Labels: type: bug report, priority: high, status: not confirmed, v4
