### ISSUE TITLE
When buying resources it takes your coins and resets resources.

### ISSUE THREAD

**Issue by vqnish** [Jexactyl/Jexactyl#218] opened 2022-12-06 21:08 UTC
### Current Behavior

When you buy any type of resources (ram,CPU,disk, etc) it removes your coins as if you bought it and it resets your resources to the amount of resources you bought. For example if you have 300% CPU and buy +50% CPU it resets it to 50% CPU.
https://streamable.com/7kxuo9

### Expected Behavior

The expected behavior would be it buys the resources and adds it to your resource count instead of resetting it.

### Steps to Reproduce

Go to panel
Get coins 
Go to store and buy any resource
Go back to your resources and you will see nothing changed but your coins will not be there anymore.

### Panel Version

3.6.2

### Wings Version

1.11

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment] 2022-12-06 21:14
Duplicate of #212

**Closed as completed by camwhi-te** 2022-12-06 21:14 UTC
