### ISSUE TITLE
Bring ability to see egg installation progress back

### ISSUE THREAD

**Issue by diedyesterdaywashere** [Jexactyl/Jexactyl#323] opened 2023-07-17 19:48 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I believe vanilla pterodactyl panel allows you to see the egg being installed in the console, but in jexactyl all you get is a screen that just tells you that server is being installed, which does not help with egg debug at all. This would really help with creating eggs, because you can't get an installation logs from wings unless installation was completed.

**Comment by ItzBenoitXD** [comment] 2023-07-17 23:52
duplicate of #68

**Closed** 2023-07-18 01:01 UTC
