### ISSUE TITLE
When creating a server, only one docker image is used

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#5] opened 2022-06-18 10:12 UTC
### Current Behavior

If user creates a server, for example: discord.py. It creates with the java 17 image. Users cant also change the image. 

### Expected Behavior

If user creates an server it should get the default egg and allow the user to change the image.

### Steps to Reproduce

Panel > Shop > Create an server > Select an server wich is not using java

### Panel Version

3.0.1

### Wings Version

1.6.1

### Games and/or Eggs Affected

Python generic, NodeJS generic, Go generic, every other non java egg

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by cmrxnn** [comment] 2022-06-18 11:38
Unable to reproduce at the provided resolution using Firefox ![image](https://cdn.discordapp.com/attachments/887033539252588555/987682652796616774/unknown.png)

**Comment by OlekAleksander** [comment] 2022-06-18 18:14
Will this be fixed in 3.1.0?

**Comment by camwhi-te** [comment] 2022-06-18 18:36
Fixed in 0e155b1

**Closed as completed by camwhi-te** 2022-06-18 18:36 UTC
Labels: type: bug report, priority: high
