### ISSUE TITLE
Location and node picker.

### ISSUE THREAD

**Issue by ghost** [Jexactyl/Jexactyl#74] opened 2022-08-01 15:48 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Like there is an egg picker while installation, I like it if there would be a location picker and node picker.

### Describe the solution you'd like.

There should be a drop-down. Showing available nodes and their locations. An unavailable node should show with disabled gray button.

**Comment by camwhi-te** [comment] 2022-08-03 01:15
Duplicate of #71

**Closed as completed by camwhi-te** 2022-08-03 01:15 UTC
