### ISSUE TITLE
Renewal card still shows even if renewal is disabled

### ISSUE THREAD

**Issue by b4dsk** [Jexactyl/Jexactyl#118] opened 2022-08-25 16:27 UTC
### Current Behavior

- Renewal card on the server console page still shows even if renewal is disabled

### Expected Behavior

- It shouldn't show, or at least say "Disabled"
- I removed the card on my own panel so it should look fine if it's not there

### Steps to Reproduce

1. Disable renewal
2. Create a server
3. Check the console page of the server

### Panel Version

3.4.2

### Wings Version

1.7.0

### Games and/or Eggs Affected

All

### Docker Image

No need

### Error Logs

```bash
No need
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by cmrxnn** [comment] 2022-08-25 17:17
Unable to reproduce this issue. +1's are appreciated.

**Comment by cmrxnn** [comment] 2022-08-25 23:10
Unable to reproduce, closing

**Closed by cmrxnn** 2022-08-25 23:10 UTC
Labels: bug, cannot reproduce, not confirmed

**Comment by BasToTheMax** [comment] 2022-08-31 15:48
I have the same issue

**Comment by BasToTheMax** [comment] 2022-08-31 15:50
I think I know how to reproduce this:

- Install pterodactyl
- create some servers
- migrate to Jexactyl
- disable renewing in the admin panel
- check the console page for the result
