### ISSUE TITLE
Admin panel sidebar bug

### ISSUE THREAD

**Issue by Groot239** [Jexactyl/Jexactyl#224] opened 2022-12-11 12:31 UTC
### Current Behavior

![Screenshot_2022-12-11-17-59-05-94_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/84964134/206903568-b719154b-6b48-4a87-b9ef-5a98b36e75f9.jpg)
Sidebar is glitched

### Expected Behavior

Sidebar need to be like this
![Screenshot_2022-12-11-18-00-33-89_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/84964134/206903624-668c1e67-05ed-48cf-bd57-0c019af64836.jpg)

### Steps to Reproduce

I didn't understand what this mean.

### Panel Version

3.6.3

### Wings Version

1.11.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by heyitslumi** [comment] 2022-12-11 12:36
duplicate of issue 152

**Closed as completed** 2022-12-11 12:58 UTC
