### ISSUE TITLE
Server creation too many attempts

### ISSUE THREAD

**Issue by Aidenw210** [Jexactyl/Jexactyl#302] opened 2023-05-25 22:08 UTC
### Current Behavior

When I tried creating a server from the store, it said "Too many attempts" in red.
![image](https://github.com/Jexactyl/Jexactyl/assets/58526185/02666475-770e-4903-bafd-450b343ba24e)

### Expected Behavior

I'm supposed to be able to create a server normally and add/remove the resources I want from a server.

### Steps to Reproduce

Go to your panel's store, click on "Create" at the bottom, fill in the required fields such as resources, etc, then scroll down and click "Create".

### Panel Version

3.7.1

### Wings Version

1.11.6

### Games and/or Eggs Affected

All eggs / nests

### Docker Image

Not egg specific

### Error Logs

```bash
https://pteropaste.com/y3gtb45343a9
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment] 2023-05-25 22:09
Duplicate of #301

**Closed as completed by camwhi-te** 2023-05-25 22:09 UTC
