### ISSUE TITLE
Delete server broken

### ISSUE THREAD

**Issue by WinterFe** [Jexactyl/Jexactyl#175] opened 2022-11-04 03:06 UTC
### Current Behavior

![image](https://user-images.githubusercontent.com/42700057/199876406-f2529cd9-d212-4efb-82c0-1dfea782ff3f.png)

### Expected Behavior

Server gets deleted

### Steps to Reproduce

Server -> Settings -> Delete Server

### Panel Version

canary (Built from git)

### Wings Version

1.7.2

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
https://bin.ptdl.co/thzv5/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Kilemsam** [comment] 2022-11-04 05:21
Duplicate of #165 

💀

**Comment by Kilemsam** [comment] 2022-11-04 05:23
Wait, what is canary panel version?

**Comment by WinterFe** [comment] 2022-11-05 01:35
> Wait, what is canary panel version?

it’s what the version reports back as in pterodactyl.
I just cloned the github and built from it



> Duplicate of #165
> 
> 💀

These issues were closed as completed and fixed, despite me still getting the same issue

**Comment by Kilemsam** [comment] 2022-11-05 08:31
> 
It's not reason create new issue bug report because "These issues were closed as completed and fixed", if it's closed and fixed - don't create one more same problem when this bug was already told and fixed

**Comment by camwhi-te** [comment] 2022-11-06 00:04
You'll be getting the same issue because the release has not been made yet.

**Closed as completed by camwhi-te** 2022-11-06 00:04 UTC
Labels: status: not confirmed
