### ISSUE TITLE
Nest Creation Error

### ISSUE THREAD

**Issue by xlelordsOntop** [Jexactyl/Jexactyl#300] opened 2023-05-25 20:00 UTC
### Current Behavior

When you make a New Nest Component It brings u to a server 500 error page

### Expected Behavior

it should've created the nest not bring u to a error page

### Steps to Reproduce

When u press create It brings u to a server error 500 screen

### Panel Version

3.7.1

### Wings Version

1.11.6

### Error Logs

```bash
Server Error 500
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [ ] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [ ] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by adr-1an** [comment] 2023-05-25 20:21
same for me

**Comment by cmrxnn** [comment] 2023-05-25 21:38
Duplicate of #296

**Closed by cmrxnn** 2023-05-25 21:38 UTC
